version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: job-finder-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    ports:
      - "3306:3306"
    volumes:
      - ../mysql_data:/var/lib/mysql
    command: --skip-log-bin --skip-name-resolve
